[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

build_unflags =
    -std=gnu++11

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -Wall

lib_deps =
    tzapu/WiFiManager

lib_extra_dirs =
    ../LaunchDisplay/.pio/libdeps/esp32-c3-devkitm-1
    /Users/davebush/Documents/Codex/local-flight-radar-sleep-work/.pio/libdeps/esp32-s3-devkitc
